# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 579)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0#3c1053, stop:1 #ad5389);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_service = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.name_service.setFont(font)
        self.name_service.setStyleSheet("background: rgba(255, 255, 255, 0.5);\n"
"height: 29px;\n"
"border-radius: 10px;\n"
"border: 0;\n"
"padding: 10px;\n"
"color: white;\n"
"font-size: 24px;")
        self.name_service.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.name_service.setObjectName("name_service")
        self.horizontalLayout.addWidget(self.name_service)
        self.email_service = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.email_service.setFont(font)
        self.email_service.setStyleSheet("background: rgba(255, 255, 255, 0.5);\n"
"height: 29px;\n"
"border-radius: 10px;\n"
"border: 0;\n"
"padding: 10px;\n"
"color: white;\n"
"font-size: 24px;")
        self.email_service.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.email_service.setObjectName("email_service")
        self.horizontalLayout.addWidget(self.email_service)
        self.passw_service = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.passw_service.setFont(font)
        self.passw_service.setStyleSheet("background: rgba(255, 255, 255, 0.5);\n"
"height: 29px;\n"
"border-radius: 10px;\n"
"border: 0;\n"
"padding: 10px;\n"
"color: white;\n"
"font-size: 24px;")
        self.passw_service.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.passw_service.setObjectName("passw_service")
        self.horizontalLayout.addWidget(self.passw_service)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.list_service = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.list_service.setFont(font)
        self.list_service.setAutoFillBackground(False)
        self.list_service.setStyleSheet("background: rgba(245, 245, 245, 0.8); color: black;")
        self.list_service.setObjectName("list_service")
        self.list_service.setColumnCount(0)
        self.list_service.setRowCount(0)
        self.verticalLayout.addWidget(self.list_service)
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setStyleSheet("border: 0;\n"
"border-radius: 10px;\n"
"font-size: 24px;\n"
"padding: 10px;\n"
"background: rgb(12, 189, 18);\n"
"color: white;\n"
"")
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        self.del_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_btn.setStyleSheet("border: 0;\n"
"border-radius: 10px;\n"
"font-size: 24px;\n"
"padding: 10px;\n"
"background: rgb(198, 0, 0);\n"
"color: white;\n"
"")
        self.del_btn.setObjectName("del_btn")
        self.verticalLayout.addWidget(self.del_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_service.setPlaceholderText(_translate("MainWindow", "Название"))
        self.email_service.setPlaceholderText(_translate("MainWindow", "Email or Login"))
        self.passw_service.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.add_btn.setText(_translate("MainWindow", "Добавить"))
        self.del_btn.setText(_translate("MainWindow", "Удалить"))
